import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

  
export const onRequest = createPagesFunctionHandler({
    build,
    getLoadContext: (context) => {
        // Validate environment variables
        const requiredEnvVars = [
            'SESSION_SECRET',
            'SUPABASE_URL',
            'SUPABASE_ANON_KEY',
            'GOOGLE_CLIENT_ID',
            'GOOGLE_CLIENT_SECRET'
        ];
        
        const missingEnvVars = requiredEnvVars.filter(
            key => !context.env[key]
        );

        if (missingEnvVars.length > 0) {
            console.error('Missing required environment variables:', missingEnvVars);
        }

        return {
            platform: context.platform,
            env: context.env,
            cloudflare: context
        };
    }
});
