[vars]
SUPABASE_URL = "@env.SUPABASE_URL"
SUPABASE_ANON_KEY = "@env.SUPABASE_ANON_KEY"
SESSION_SECRET = "@env.SESSION_SECRET"
GOOGLE_CLIENT_ID = "@env.GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "@env.GOOGLE_CLIENT_SECRET"